[package]
name = "ibc-rpc"
description = "RPC apis for substrate ibc"
edition = "2021"
version = "0.1.0"
authors = ["David Salami <wizdave97@gmail.com>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true }
ibc-primitives = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
pallet-ibc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

frame-system = { workspace = true }
ibc-proto = { workspace = true, default-features = false }
ibc-runtime-api = { workspace = true }
sc-chain-spec = { workspace = true, default-features = false }
sc-client-api = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
sp-blockchain = { workspace = true, default-features = false }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-trie = { workspace = true }
tendermint-proto = { workspace = true }
ibc = { workspace = true, default-features = false }
ibc-derive = { workspace = true, default-features = false }
