[package]
edition = "2021"
name = "ibc-runtime-api"
version = "0.1.0"
authors = ["David Salami <wizdave97@gmail.com>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ibc-primitives = { workspace = true }
pallet-ibc = { workspace = true, default-features = false }
sp-api = { workspace = true }
sp-std = { workspace = true }
parity-scale-codec = { workspace = true }

[features]
default = ['std']
std = ['sp-api/std', 'sp-std/std', 'ibc-primitives/std', 'pallet-ibc/std', 'parity-scale-codec/std']
