[package]
name = "beefy-prover"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>", "David Salami <wizdave97@gmail.com>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
anyhow = "1.0.66"
once_cell = "1.16.0"
# subxt-codegen = { package = "codegen", path = "../../../utils/subxt/codegen" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dependencies]
sp-std = { workspace = true }
sp-runtime = { workspace = true }
sp-core =  { workspace = true }
sp-io = { workspace = true }
sp-core-hashing = { workspace = true }
frame-support = { workspace = true }
pallet-beefy-mmr = { workspace = true }
pallet-mmr = { workspace = true }
sp-mmr-primitives = { workspace = true }
sp-consensus-beefy = { workspace = true }
parity-scale-codec = { workspace = true }
rs_merkle = { workspace = true }
derive_more = { workspace = true, features = ["from"]  }
light-client-common = { workspace = true, features = ["enable-subxt"] }
jsonrpsee-core = { workspace = true, features = ["async-client"] }

# Optional deps
subxt = { workspace = true, features = ["substrate-compat"] }
hex-literal = { workspace = true }
serde_json = { workspace = true }
mmr-rpc = { workspace = true }
sp-trie = { workspace = true }
hex = { workspace = true }
beefy-light-client-primitives = { workspace = true }

[dev-dependencies]
light-client-common = { workspace = true }
