[package]
name = "tangle-subxt"
version ={ workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
default = ["std"]
std = [
    "subxt/native",
    "subxt/jsonrpsee",
]
wasm = [
    "subxt/web",
    "subxt/jsonrpsee",
    "getrandom/js"
]

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
subxt = { version = "0.34.0", default-features = false }
getrandom = { workspace = true, optional = true }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.7.0" }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.7.0" }
tangle-crypto-primitives = { path = "../primitives/crypto" }
hex = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
subxt-signer = { version = "0.34.0", default-features = false, features = ["subxt", "sr25519", "native"] }
tokio = { version = "1.32.0", features = ["full"] }

[target.'cfg(all(target_family = "wasm"))'.dev-dependencies]
subxt-signer = { version = "0.34.0", default-features = false, features = ["subxt", "sr25519", "web"] }
tokio = { version = "1.32.0", features = ["time", "rt", "sync", "macros", "io-util"] }
wasm-bindgen-test = "0.3.0"