[package]
edition = "2021"
name = "ibc-primitives"
version = "0.1.0"
authors = ["David Salami <wizdave97@gmail.com>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

ripemd = { version = "0.1.1", default-features = false }
scale-info = { version = '2.1.1', default-features = false }
serde = { workspace = true, optional = true }
sha2 = { version = "0.10.2", default-features = false }
sha3 = { version = "0.10.1", default-features = false }
hex = { version = "0.4.3", default-features = false }
base58 = "0.2.0"
blake2 = { version = "0.10", default-features = false }

sp-core = { workspace = true }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true }
sp-runtime-interface = { workspace = true, default-features = false }
sp-std = { workspace = true }
sp-trie = { workspace = true }
frame-support = { workspace = true }

parity-scale-codec = { workspace = true }
ibc = { workspace = true }

[features]
default = ['std']
std = [
	"parity-scale-codec/std",
	"serde",
	"ibc/std",
	"scale-info/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-runtime-interface/std",
	"sp-io/std",
	"sp-trie/std",
	"sha2/std",
	"sha3/std",
	"ripemd/std",
	"frame-support/std",
	"hex/std",
	"blake2/std",
	"serde/std"
]
mocks = []
runtime-benchmarks = []
